py11-pytest:
  image: python:3.11
  script:
    - apt-get update -q -y
    - pip install pytest
    - pip install .
    - mkdir -p data/tests/springer
    - cp "$JCONV_SPRINGER_ARTICLE" data/tests/springer/article.xml
    - ls -lsh data/tests/springer/
    - pytest --pyargs vzg.jconv
